UserChatProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
]

if settings.DEBUG:
    # import debug_toolbar
    # urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    # uncomment if you removed above temporary
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (SignUpView, UserLoginView, UserLogoutView, CustomPasswordResetView,UserProfileView, 
DeleteProfileImage, Home, ChatGroupFormView, ChatGroupListView, ChatGroupMessageView)
app_name = 'users'
urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('group-add/',ChatGroupFormView.as_view(),name="chat-group-add"),
    path('group-list/', ChatGroupListView.as_view(), name='group-list'),
    path('chat/<int:pk>/',ChatGroupMessageView.as_view(),name="chat-group-update"),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('profile/', UserProfileView.as_view(), name='user-profile'),
    path('delete-image/', DeleteProfileImage.as_view(), name='delete-image'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('', include('django.contrib.auth.urls')),
]

templates/base.html
{% load static %}
{% load tz %}
{% load l10n %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="description"
    content="Django Base User Chat Project" />
  <meta name="keywords" content="user, chat, django" />
  <meta name="author" content="satinder" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes, minimal-ui" />
  {% comment %}
  <meta http-equiv="refresh" content="3"> {% endcomment %}
  <title>{% block title %} Django Chat{% endblock title %} </title>
  <!-- Fevicon -->
  <!-- Favicons -->
  <link rel="icon" href="{% static 'img/favicon.ico' %}" sizes="32x32" />

  <link rel="icon" href="{% static 'assets/images/cropped-favicon-32x32.png' %}" sizes="32x32" />
  <link rel="icon" href="{% static 'assets/images/cropped-favicon-192x192.png' %}" sizes="192x192" />
  <link rel="apple-touch-icon-precomposed" href="{% static 'assets/images/cropped-favicon-180x180.png' %}" />
{% block base_css %}

  {% include "base/css.html" %}
{% endblock base_css %}
  
  <style>
    .LoaderBalls {
      width: 90px;
      display: flex;
      justify-content: space-between;
      align-items: center;
      position: fixed;
      z-index: 99999;
      left: 50%;
      top: 30%;
      transform: translate(-50%, -50%);
    }

    .LoaderBalls__item {
      width: 20px;
      height: 20px;
      border-radius: 50%;
      background: #0094ca;

    }

    .LoaderBalls__item:nth-child(1) {
      animation: bouncing 0.4s alternate infinite cubic-bezier(0.6, 0.05, 0.15, 0.95);
    }

    .LoaderBalls__item:nth-child(2) {
      animation: bouncing 0.4s 0.1s alternate infinite cubic-bezier(0.6, 0.05, 0.15, 0.95) backwards;
    }

    .LoaderBalls__item:nth-child(3) {
      animation: bouncing 0.4s 0.2s alternate infinite cubic-bezier(0.6, 0.05, 0.15, 0.95) backwards;
    }

    @keyframes bouncing {
      0% {
        transform: translate3d(0, 10px, 0) scale(1.2, 0.85);
      }

      100% {
        transform: translate3d(0, -20px, 0) scale(0.9, 1.1);
      }
    }
  </style>
  <script>
    document.onreadystatechange = function () {
      if (document.readyState !== "complete") {
        document.querySelector("body").style.visibility = "hidden";
        document.querySelector(".LoaderBalls").style.visibility = "visible";
      } else {
        document.querySelector(".LoaderBalls").style.display = "none";
        document.querySelector("body").style.visibility = "visible";
      }
    };  
  </script>
  <noscript>

    <style>
      /* noscript detects if javascript is disabled
		   if JavaScript not present, don't show loader */

      .LoaderBalls {
        display: none;
      }
    </style>

  </noscript>
</head>

<body class="vertical-layout dark-outer-color-theme">
  <div class="LoaderBalls">
    <!-- https://codepen.io/Sixclones/pen/VBdeXL -->
    <div class="LoaderBalls__item"></div>
    <div class="LoaderBalls__item"></div>
    <div class="LoaderBalls__item"></div>
  </div>
  {% block indexhtml %} {% endblock indexhtml %}

  {% include "base/js.html" %}
  {% block javascript%}
  {% endblock javascript%}


</body>

</html>

templates/chat_group_detail.html
{% load static %}

<!-- Start col -->
<div class="col-sm-5 col-xl-4">
    <div class="chat-list  h-100 card-bg-color">
        <!-- <div class="chat-search">
            <form>
                <div class="input-group">
                    <input type="search" class="form-control" placeholder="Search" aria-label="Search"
                        aria-describedby="button-addon3">
                    <div class="input-group-append">
                        <button class="btn" type="submit" id="button-addon3"><i class="ri-search-2-line"></i></button>
                    </div>
                </div>
            </form>
        </div> -->
        <div class="chat-user-list">
            <ul class="list-unstyled mb-0" >
                {% for t in chat_group_object_list %}
                {% url 'users:chat-group-update' pk=t.pk  as group_path %}
                <a href="{{t.get_update_url}}"  >
                <li class="media dark-theme-text {% if group_path == request.path  %}{% if forloop.first or forloop.last %}{% else %}rounded-0{% endif %} chat-active{% endif %}">
                    <img class="align-self-center rounded-circle chat-profile-img-sm" src="{{t.user_avatar_url}}"
                    alt="">
                    <div class="media-body">
                        <h5>{{t.name|truncatewords:4 }}<span class="timing text-dark">{{t.created_at|date:"D d M y"}}</span>
                        </h5>
                    </div>
                </li>
                </a>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
<!-- End col -->
{% if chat_group_object %}
<!-- Start col -->
<div class="col-sm-7 col-xl-8">
    <div class="chat-detail h-100 card-bg-color-lighter">
        <div class="chat-head">
            <ul class="list-unstyled mb-0">
                <li class="media">
                    <img class="align-self-center mr-3 rounded-circle chat-profile-img" src="{{chat_group_object.user_avatar_url}}"
                        alt="">
                    <div class="media-body">
                        <h5 class="font-24  dark-theme-text">{{chat_group_object.name}}</h5>
                        <!-- <p class="mb-0  dark-theme-text">Assigned to: {{chat_group_object.user.name}} </p> -->
                    </div>
                </li>
            </ul>
        </div>
        
        <div class="chat-body ">
            {% include 'chat_message.html' with chat_message_form=chat_message_form form_action_url=chat_group_object.get_update_url chat_messages=chat_group_object.messages themeclass="dark-theme-text" %}
        </div>
        
    </div>
</div>
<!-- End col -->
{% endif %}

templates/chat_group_form.html
{% load static %}
<form  method="post" accept-charset="utf-8"  class="col"
    action="{% if chat_group_object %}{{chat_group_object.get_update_url}}{% else %}{% url 'users:chat-group-add' %}{% endif %}"
    autocomplete="off">
    <div class="card details-card bgc-none">
        <h2 class="card-header header-bgc header-box-shadow py-0">Add New Group</h2>

        <div class="card-body py-0 ">
            {% csrf_token %}
            <div class="form-row">
                {% include 'form_repeat.html' with f=chat_group_form.name f_label="Name" col_md="6" %}
                <div class="form-group col-md-1">
                    <label for="" class="col-sm-12  col-form-label font-weight-bold text-nowrap dark-theme-text">Save</label>
                    <button type="submit" class="btn btn-outline-primary">Save</button>
                </div>
                <div class="form-group col-md-1">
                    <label for="" class="col-sm-12  col-form-label font-weight-bold text-nowrap dark-theme-text">Reset</label>
                    <button type="reset" class="btn btn-outline-dark">Reset</button>
                </div>
            </div>
        </div>
    </div>

</form>

templates/chat_group_page.html
{% extends "home.html" %} {% load static %}
{% block title %}Create New Chat Group{% endblock title %}
{% block breadcrumbbar %}

<!-- Start Breadcrumbbar -->

<div class="breadcrumbbar bg-transparent">
  {% comment %} <div class="row align-items-center">
    <div class="col-md-auto col-lg-auto">
      <div class="media">
        <span class="breadcrumb-icon"><i class="ri-menu-add-line"></i></span>
        <div class="media-body ">
          <h3 class="page-title mt-2">BOMS</h3>
        </div>
      </div>
    </div>
  </div> {% endcomment %}
</div>

<!-- End Breadcrumbbar -->

{% endblock breadcrumbbar %}


{% block content %}

<div class="contentbar dark-outer-color-theme pt-5">
  <div class="row justify-content-center dark-outer-color-theme">
    {% if chat_group_form %}
    {% include 'chat_group_form.html' %}
    
    {% else %}
 

    <div class="w-100"></div>


    <!-- start chat  bom -->
    {% include 'chat_group_detail.html' %}
    <!-- end chat  bom-->

{% endif %}

  </div>
</div>

{% endblock content %}

templates/chat_message.html
{% load tz %}
{% with chat_messages_count=chat_messages.count %}
{% if chat_messages_count %}
<div class="text-center mb-2">
<span class="badge badge-light text-dark">{{ chat_messages_count }} message{{ chat_messages_count|pluralize }}</span>
</div>




{% for message in chat_messages %}

{% if user == message.user %}

<div class="text-center mt-2">
</div>
  <div class="card-bg-color p-1 user-chat-border currunt-user-border">
  <div class="row col justify-content-end">
<span class="font-10"  >{{message.timestamp|timesince}} ago</span>
  </div>
<div class="row my-2 ml-2 justify-content-end">
  <div class="col-auto pl-5 font-weight-bold ">{{ message.message }}</div>
</div>
  </div>

  {% else %}

<div class="text-center mt-2">
</div>

<div class="card-bg-color p-1 user-chat-border other-user-border">
<div class="row main-message justify-content-start">
  <div class="col-auto pr-1 my-auto">
    <img src="{{ message.user_avatar_url }}" class="img-fluid my-1 comment-user-img comment-user-img-smborder-0" alt="">
  </div>
  <div class="col-auto p-1 my-auto text-nowrap">
  {% spaceless %}
    <span    
    style="color: {% ifchanged message.user.name %}
          {% cycle 'darkblue' 'darkred' 'indigo' 'mediumblue' %}
          {% else %}darkblue{% endifchanged %}">
          {{ message.user.name|default:"User"}}</span>
  {% endspaceless %}
<span class="font-10" >{{message.timestamp|timesince}} ago</span>
  </div>
  
</div>
<div class="row  my-2 ml-2 justify-content-start">
  <div class="col-auto pl-5 font-weight-bold ">{{ message.message }}</div>
</div>

</div>

  {% endif %}
  {% if not forloop.last %}
      <hr class="mb-0" />
  {% endif %}
{% endfor %}

{% endif %}

{% endwith %}

{% if request.user.is_authenticated %}

<form  method="post" action="{{form_action_url}}" autocomplete="off">
  {% csrf_token %}
  <div class="form-row">
    <div class="form-group col-10">
      {{chat_message_form.message}}
      {{chat_message_form.user.as_hidden}}
      {{chat_message_form.content_type.as_hidden}}
      {{chat_message_form.object_id.as_hidden}}
    </div>
    <div class="form-group col-2 align-self-center">
      <button type="submit" class="btn btn-sm btn-primary p-1">message</button>
    </div>
  </div>
</form>
{% else %}
<p>You must login to message </p>
{% endif %}

templates/form_repeat.html
<div class="form-group col-md-{{col_md|default:"4"}} {{mr_lg_auto}} {{exclass}} ">
    <label for="{{f.id_for_label}}" class="col-sm-{{lcol|default:"6"}} {{lclass}} col-form-label font-weight-bold dark-theme-text">{{f_label}}</label>
    <div class="col-sm-12">
        {{f}}
    </div>
    {% if f.errors %} {% for ee in f.errors %}
    <span class="error-text text-center">
        {{ ee }}
    </span>
    {% endfor %} {% endif %}
</div>

templates/getprams.html
{% block getprams %}
{% if page and fp %}?page={{page}}
{% for p,v in request.GET.items %}
{% if p != 'page' and v != "" %}&{{p}}={{v}}{% endif %}
{% endfor %}
{% elif fp %}{% if request.GET %}?{% endif %}
{% for p,v in request.GET.items %}
{% if p != 'page' and v != "" %}{% if not forloop.first %}&{% endif %}{{p}}={{v}}{% endif %}
{% endfor %}
{% else %}{% if request.GET %}?{% endif %}
{% for p,v in request.GET.items %}
{% if v != "" %}{% if not forloop.first %}&{% endif %}{{p}}={{v}}{% endif %}
{% endfor %}
{% endif %}
{% endblock getprams %}

templates/home.html
{% extends "index.html" %}
{% load static %}
{% block title %} DashBoard {% endblock title %} 
{% block base_css %}
{{block.super}}
{% endblock base_css %}
{% block breadcrumbbar %}
<div class="breadcrumbbar bg-transparent ">

</div>
{% endblock breadcrumbbar %}


<!-- End Contentbar -->
{% block content %}
{% endblock content %}

{% block javascript %}
{% endblock javascript %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% block base_css %}
{{block.super}}
{% endblock base_css %}
{% block indexhtml %}


<!-- Start Infobar Setting Sidebar -->
<div id="infobar-settings-sidebar" class="infobar-settings-sidebar card-bg-color">
    <div class="infobar-settings-sidebar-head d-flex w-100 justify-content-between">
        <h4>Settings</h4><a href="javascript:void(0)" id="infobar-settings-close" class="infobar-settings-close"><i
                class="ri-close-line menu-hamburger-close"></i></a>
    </div>
    <div class="infobar-settings-sidebar-body">
        <div class="custom-mode-setting">
            <div class="row align-items-center pb-3">
                <div class="col-12">
                    <h6 class="mb-1 text-center">Choose a Color Theme</h6>
                </div>
                <div class="col-12 pb-1">
                    <div id="theme-options-wrapper">
                        <div data-mode="light" id="light-mode" class="theme-dot"></div>
                        <div data-mode="blue" id="blue-mode" class="theme-dot"></div>
                        <div data-mode="green" id="green-mode" class="theme-dot"></div>
                        <div data-mode="purple" id="purple-mode" class="theme-dot"></div>
                        <div data-mode="white" id="white-mode" class="theme-dot"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="infobar-settings-sidebar-overlay"></div>
<!-- End Infobar Setting Sidebar -->
<!-- Start Containerbar -->
<div id="containerbar px-0">
 
    <!-- Start Rightbar -->
    <div class="rightbar">
    {% include 'base/rightbar.html' %}

    {% block breadcrumbbar %}
            <!-- Start rightbar Breadcrumbbar -->
            <div class="breadcrumbbar bg-transparent">
            
            </div>
            <!-- End rightbar Breadcrumbbar -->
    {% endblock breadcrumbbar %}


    {% block content %}



    {% endblock content %}


    </div>
    <!-- End Rightbar -->

</div>
<!-- End Containerbar -->

<script type="text/javascript">
    let static = "{% static 'colorscheme/css' %}"
</script>
{% endblock indexhtml %}

templates/pagination.html
{% block paginationblock %}
{% if is_paginated %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <span><a class="page-link"
                                href="{% include 'getprams.html' with fp=True  qr=True page=i %}">Previous</a></span>
                    </li>
                    {% endif %}
                    {% for i in page_obj.paginator.page_range %}
                        {% if page_obj.number == i %}
                        <li class="page-item active"><a class="page-link"
                                href="{% include 'getprams.html' with fp=True  qr=True page=i %}">{{ i }}</a></li>
                        {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
                        <li class="page-item"><a class="page-link"
                                href="{% include 'getprams.html' with fp=True  qr=True page=i %}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
                        <li class="page-item"><a class="page-link"
                                href="{% include 'getprams.html' with fp=True  qr=True page=page_obj.number|add:'5' %}">...</a></li>
                        <li class="page-item"><a class="page-link"
                                href="{% include 'getprams.html' with fp=True  qr=True page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a></li>
                    {% endif %}
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <span><a class="page-link"
                                    href="{% include 'getprams.html' with fp=True  qr=True page=page_obj.next_page_number %}">Next</a></span>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
</div>
{% endif %}
{% endblock paginationblock %}